webtalk_init -webtalk_dir C:/Workplace/DSDLab/Lab02/ex1_full_adder/ex1_full_adder.sim/sim_1/impl/func/xsim/xsim.dir/full_adder_1bit_tb_func_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 20 22:20:39 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5898e338-f9d7-4306-b319-25868422e9a9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "23bdc9ad2f16410eb67dc21791a3dcd2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8924_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1152942382 -regid "" -xml C:/Workplace/DSDLab/Lab02/ex1_full_adder/ex1_full_adder.sim/sim_1/impl/func/xsim/xsim.dir/full_adder_1bit_tb_func_impl/webtalk/usage_statistics_ext_xsim.xml -html C:/Workplace/DSDLab/Lab02/ex1_full_adder/ex1_full_adder.sim/sim_1/impl/func/xsim/xsim.dir/full_adder_1bit_tb_func_impl/webtalk/usage_statistics_ext_xsim.html -wdm C:/Workplace/DSDLab/Lab02/ex1_full_adder/ex1_full_adder.sim/sim_1/impl/func/xsim/xsim.dir/full_adder_1bit_tb_func_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
