# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 32
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/project/lab03.cache/wt [current_project]
set_property parent.project_path C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/project/lab03.xpr [current_project]
set_property default_lib default [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/project/lab03.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library default {
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/hdl/decoder_3_to_8.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/hdl/frequency_divider.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/hdl/types.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/hdl/seven_segments_display_decoder.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/hdl/seven_segments_display_driver.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/hdl/top_module.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/xdc/top_module.xdc
set_property used_in_implementation false [get_files C:/Workplace/SUSTech-EE332-Digital-System-Designing-Laboratory/Lab03/lab03/src/xdc/top_module.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
