@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Mar 15 00:40:10 +0800 2023
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 01692192fe01458bbd1b1f9a8fb15a31 --incr --debug typical --relax --mt 32 -L xil_defaultlib -L secureip --snapshot top_module_tb_behav xil_defaultlib.top_module_tb -log elaborate.log"
call xelab  -wto 01692192fe01458bbd1b1f9a8fb15a31 --incr --debug typical --relax --mt 32 -L xil_defaultlib -L secureip --snapshot top_module_tb_behav xil_defaultlib.top_module_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
